export const searchLanguageConstants = {
  en: {
    search: "Search",
    gptSearchPlaceholder: "What do you like to watch today?",
    playBtn: "Play",
    addMoreBtn: "Add More",
    nowPlaying: "Now Playing",
    popular: "Popular",
    upcoming: "Upcoming",
    signOut: "Sign Out",
    GPTSearch: "GPT Search",
    language: "Language",
    rating: "Rating",
    releaseDate: "Release Date",
  },
  ja: {
    search: "検索",
    gptSearchPlaceholder: "今日は何を見たいですか？",
    playBtn: "再生",
    addMoreBtn: "追加",
    nowPlaying: "再生中",
    popular: "人気",
    upcoming: "今後",
    signOut: "サインアウト",
    GPTSearch: "GPT検索",
    language: "言語",
    rating: "評価",
    releaseDate: "公開日",
  },
  ko: {
    search: "검색",
    gptSearchPlaceholder: "오늘 뭐 보고 싶어요?",
    playBtn: "재생",
    addMoreBtn: "더 추가",
    nowPlaying: "현재 상영 중",
    popular: "인기",
    upcoming: "다가오는",
    signOut: "로그아웃",
    GPTSearch: "GPT 검색",
    language: "언어",
    rating: "평점",
    releaseDate: "개봉일",
  },
  zh: {
    search: "搜索",
    gptSearchPlaceholder: "今天想看什么？",
    playBtn: "播放",
    addMoreBtn: "添加更多",
    nowPlaying: "正在播放",
    popular: "热门",
    upcoming: "即将上映",
    signOut: "登出",
    GPTSearch: "GPT搜索",
    language: "语言",
    rating: "评分",
    releaseDate: "发布日期",
  },
  hi: {
    search: "खोज",
    gptSearchPlaceholder: "आज आप क्या देखना पसंद करेंगे?",
    playBtn: "प्ले करें",
    addMoreBtn: "और जोड़ें",
    nowPlaying: "अभी चल रहा है",
    popular: "लोकप्रिय",
    upcoming: "आगामी",
    signOut: "साइन आउट",
    GPTSearch: "जीपीटी खोज",
    language: "भाषा",
    rating: "रेटिंग",
    releaseDate: "प्रकाशन तिथि",
  },
  es: {
    search: "Buscar",
    gptSearchPlaceholder: "¿Qué te gustaría ver hoy?",
    playBtn: "Jugar",
    addMoreBtn: "Agregar más",
    nowPlaying: "Ahora reproduciendo",
    popular: "Popular",
    upcoming: "Próximamente",
    signOut: "Cerrar sesión",
    GPTSearch: "Búsqueda GPT",
    language: "Idioma",
    rating: "Clasificación",
    releaseDate: "Fecha de lanzamiento",
  },
  fr: {
    search: "Chercher",
    gptSearchPlaceholder: "Qu'est-ce que tu aimerais regarder aujourd'hui?",
    playBtn: "Jouer",
    addMoreBtn: "Ajouter plus",
    nowPlaying: "En cours de lecture",
    popular: "Populaire",
    upcoming: "À venir",
    signOut: "Déconnexion",
    GPTSearch: "Recherche GPT",
    language: "Langue",
    rating: "Note",
    releaseDate: "Date de sortie",
  },
  de: {
    search: "Suche",
    gptSearchPlaceholder: "Was möchten Sie heute sehen?",
    playBtn: "Spielen",
    addMoreBtn: "Mehr hinzufügen",
    nowPlaying: "Jetzt läuft",
    popular: "Beliebt",
    upcoming: "Kommend",
    signOut: "Abmelden",
    GPTSearch: "GPT-Suche",
    language: "Sprache",
    rating: "Bewertung",
    releaseDate: "Veröffentlichungsdatum",
  },
  it: {
    search: "Ricerca",
    gptSearchPlaceholder: "Cosa ti piacerebbe guardare oggi?",
    playBtn: "Giocare",
    addMoreBtn: "Aggiungi altro",
    nowPlaying: "In riproduzione",
    popular: "Popolare",
    upcoming: "In arrivo",
    signOut: "Esci",
    GPTSearch: "Ricerca GPT",
    language: "Lingua",
    rating: "Valutazione",
    releaseDate: "Data di uscita",
  },
  ru: {
    search: "Поиск",
    gptSearchPlaceholder: "Что бы вы хотели посмотреть сегодня?",
    playBtn: "Играть",
    addMoreBtn: "Добавить больше",
    nowPlaying: "Сейчас воспроизводится",
    popular: "Популярное",
    upcoming: "Скоро",
    signOut: "Выйти",
    GPTSearch: "Поиск GPT",
    language: "Язык",
    rating: "Рейтинг",
    releaseDate: "Дата выхода",
  },
  pt: {
    search: "Pesquisa",
    gptSearchPlaceholder: "O que você gostaria de assistir hoje?",
    playBtn: "Jogar",
    addMoreBtn: "Adicionar mais",
    nowPlaying: "Em reprodução",
    popular: "Popular",
    upcoming: "Próximos",
    signOut: "Sair",
    GPTSearch: "Pesquisa GPT",
    language: "Idioma",
    rating: "Classificação",
    releaseDate: "Data de lançamento",
  },
  mr: {
    search: "शोध",
    gptSearchPlaceholder: "तुम्हाला आज काय पाहायचे आहे?",
    playBtn: "प्ले करा",
    addMoreBtn: "अधिक जोडा",
    nowPlaying: "आता प्ले होत आहे",
    popular: "लोकप्रिय",
    upcoming: "आगंतुक",
    signOut: "साइन आउट करा",
    GPTSearch: "GPT शोध",
    language: "भाषा",
    rating: "रेटिंग",
    releaseDate: "प्रकट तारीख",
  },
  te: {
    search: "శోధించు",
    gptSearchPlaceholder: "ఈ రోజు మీరు ఏం చూడాలి?",
    playBtn: "ప్లే",
    addMoreBtn: "మరిన్ని జోడించండి",
    nowPlaying: "ప్రస్తుతం ప్లే అవుతోంది",
    popular: "జనప్రియ",
    upcoming: "వచ్చే",
    signOut: "సైన్ అవుట్",
    GPTSearch: "GPT శోధన",
    language: "భాష",
    rating: "రేటింగ్",
    releaseDate: "విడుదల తేదీ",
  },
  ml: {
    search: "തിരയുക",
    gptSearchPlaceholder: "ഇന്ന് നിങ്ങൾ എന്ത് കാണാനാണ്?",
    playBtn: "പ്ലേ ചെയ്യുക",
    addMoreBtn: "കൂടുതൽ ചേർക്കുക",
    nowPlaying: "ഇപ്പോൾ പ്ലേ ചെയ്യുന്നു",
    popular: "ജനപ്രിയം",
    upcoming: "വരികൾ",
    signOut: "പുറത്തോക്കുക",
    GPTSearch: "GPT തിരയൽ",
    language: "ഭാഷ",
    rating: "റേറ്റിംഗ്",
    releaseDate: "പ്രസിദ്ധീകരണ തീയതി",
  },
  ta: {
    search: "தேடு",
    gptSearchPlaceholder: "இன்று நீங்கள் என்ன பார்க்க விரும்புகிறீர்கள்?",
    playBtn: "விளையாடு",
    addMoreBtn: "மேலும் சேர்க்கவும்",
    nowPlaying: "இப்போது விளையாடுகிறது",
    popular: "பிரபலமான",
    upcoming: "வருகிறது",
    signOut: "வெளியேறு",
    GPTSearch: "GPT தேடல்",
    language: "மொழி",
    rating: "மதிப்பீடு",
    releaseDate: "வெளியீட்டு தேதி",
  },
};
