export const searchLanguageConstants = {
  en: {
    search: "Search",
    gptSearchPlaceholder: "What do you like to watch today?",
    playBtn: "Play",
    addMoreBtn: "Add More",
    nowPlaying: "Now Playing",
    popular: "Popular",
    upcoming: "Upcoming",
  },
  ja: {
    search: "検索",
    gptSearchPlaceholder: "今日は何を見たいですか？",
    playBtn: "再生",
    addMoreBtn: "追加",
    nowPlaying: "再生中",
    popular: "人気",
    upcoming: "今後",
  },
  ko: {
    search: "검색",
    gptSearchPlaceholder: "오늘 뭐 보고 싶어요?",
    playBtn: "재생",
    addMoreBtn: "더 추가",
    nowPlaying: "현재 상영 중",
    popular: "인기",
    upcoming: "다가오는",
  },
  zh: {
    search: "搜索",
    gptSearchPlaceholder: "今天想看什么？",
    playBtn: "播放",
    addMoreBtn: "添加更多",
    nowPlaying: "正在播放",
    popular: "热门",
    upcoming: "即将上映",
  },
  hi: {
    search: "खोज",
    gptSearchPlaceholder: "आज आप क्या देखना पसंद करेंगे?",
    playBtn: "प्ले करें",
    addMoreBtn: "और जोड़ें",
    nowPlaying: "अभी चल रहा है",
    popular: "लोकप्रिय",
    upcoming: "आगामी",
  },
  es: {
    search: "Buscar",
    gptSearchPlaceholder: "¿Qué te gustaría ver hoy?",
    playBtn: "Jugar",
    addMoreBtn: "Agregar más",
    nowPlaying: "Ahora reproduciendo",
    popular: "Popular",
    upcoming: "Próximamente",
  },
  fr: {
    search: "Chercher",
    gptSearchPlaceholder: "Qu'est-ce que tu aimerais regarder aujourd'hui?",
    playBtn: "Jouer",
    addMoreBtn: "Ajouter plus",
    nowPlaying: "En cours de lecture",
    popular: "Populaire",
    upcoming: "À venir",
  },
  de: {
    search: "Suche",
    gptSearchPlaceholder: "Was möchten Sie heute sehen?",
    playBtn: "Spielen",
    addMoreBtn: "Mehr hinzufügen",
    nowPlaying: "Jetzt läuft",
    popular: "Beliebt",
    upcoming: "Kommend",
  },
  it: {
    search: "Ricerca",
    gptSearchPlaceholder: "Cosa ti piacerebbe guardare oggi?",
    playBtn: "Giocare",
    addMoreBtn: "Aggiungi altro",
    nowPlaying: "In riproduzione",
    popular: "Popolare",
    upcoming: "In arrivo",
  },
  ru: {
    search: "Поиск",
    gptSearchPlaceholder: "Что бы вы хотели посмотреть сегодня?",
    playBtn: "Играть",
    addMoreBtn: "Добавить больше",
    nowPlaying: "Сейчас воспроизводится",
    popular: "Популярное",
    upcoming: "Скоро",
  },
  pt: {
    search: "Pesquisa",
    gptSearchPlaceholder: "O que você gostaria de assistir hoje?",
    playBtn: "Jogar",
    addMoreBtn: "Adicionar mais",
    nowPlaying: "Em reprodução",
    popular: "Popular",
    upcoming: "Próximos",
  },
  tl: {
    search: "Maghanap",
    gptSearchPlaceholder: "Ano ang gusto mong panoorin ngayon?",
    playBtn: "Maglaro",
    addMoreBtn: "Magdagdag ng higit pa",
    nowPlaying: "Nagpe-play ngayon",
    popular: "Sikat",
    upcoming: "Darating",
  },
  mr: {
    search: "शोध",
    gptSearchPlaceholder: "तुम्हाला आज काय पाहायचे आहे?",
    playBtn: "प्ले करा",
    addMoreBtn: "अधिक जोडा",
    nowPlaying: "आता प्ले होत आहे",
    popular: "लोकप्रिय",
    upcoming: "आगंतुक",
  },
};
